package com.model;

public enum Skill {
    FIRST_RESPONDER,
    CAN_COOK,
    HAS_POWER_TOOLS,
    CAN_DRIVE,
    SHELTER_STAFF,
    BOAT_OPERATOR,
    HEAVY_MACHINERY_OPERATOR,
    CAN_SWIM,
    HEAVY_LIFTER,
    CAN_PROVIDE_MEDICAL_ASSISTANCE,
    LANGUAGE_TRANSLATOR
}
